CREATE SEQUENCE  PG_ACCRUAL_RULE_SEQ_NUMBER  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

CREATE  TABLE PG_ACCRUAL_RULE_MASTER 
   (	AR_SEQ_NUMBER NUMBER(10,0) Primary Key, 
		AR_CONTRACTING_PARTY_FK VARCHAR2(100 BYTE) NOT NULL,
		AR_CONTRACT_NUMBER_FK NUMBER(10,0) NOT NULL, 
		AR_END_USER_FK VARCHAR2(100 BYTE), 
		AR_ACTIVE NUMBER(1,0),
		AR_LAST_UPDATED DATE,
		AR_UPDATED_BY NUMBER(10,0),
		AR_IS_DELETED NUMBER(1,0) DEFAULT 0
   ) ; 
   
   insert into PG_ACCRUAL_RULE_MASTER
(AR_SEQ_NUMBER,
AR_CONTRACTING_PARTY_FK,
AR_CONTRACT_NUMBER_FK,
AR_END_USER_FK,
AR_ACTIVE
)
values ( 1,'Prashant Gupta',11,'Prashant Gupta',1);

insert into PG_ACCRUAL_RULE_MASTER
(AR_SEQ_NUMBER,
AR_CONTRACTING_PARTY_FK,
AR_CONTRACT_NUMBER_FK,
AR_END_USER_FK,
AR_ACTIVE
)
values ( 2,'Rahul Gupta',12,'Rahul Gupta',1);